hw: m25p80: Add the write protect pin to the m25p80 model
facebookarchive/openbmc-qemu-fork pull request #17
Opened 2022-05-13 23:07 UTC by chen-iris

2022-05-13 23:08 UTC, peterdelevoryas requested changes

2022-05-13 23:08 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +    s->write_protect = true;
Should this be here?

2022-05-13 23:19 UTC, chen-iris commented on hw/block/m25p80.c
> +    s->write_protect = true;
You're right! Updated

2022-05-16 17:25 UTC, williamspatrick reviewed
I can't tell which polarity we are modeling and which way the QEMU code would tend to want to see it.  My inclination is that we would want to model the state of the function and not the state of the pin?

2022-05-16 17:25 UTC, williamspatrick commented on hw/block/m25p80.c
> +    s->write_protect = true;
Do you want the default to be `true` or `false`?  I'd kind of expect most machines to have write-protect disabled by default.

2022-05-16 17:25 UTC, williamspatrick commented on hw/block/m25p80.c
> +    /* W# is just a single pin. */
`#` is negative triggered?  Do we have the boolean in the obvious way or inverted?

"obvious": `write-protect = true` => "write protect is enabled"

2022-05-16 17:25 UTC, williamspatrick commented on hw/block/m25p80.c
> +                            m25p80_write_protect_irq_handler, "W#", 1);
Ah, here it appears as if we're modeling the state of the pin `W#` rather than the state of the function?

2022-05-16 18:51 UTC, peterdelevoryas commented
> I can't tell which polarity we are modeling and which way the QEMU code would tend to want to see it.  My inclination is that we would want to model the state of the function and not the state of the pin?

Hmmmm yeah I guess that makes sense. You're referring to the fact that "high" on the pin actually means "don't protect", and "low" is used to enable hardware protected mode, which is kind of the inverse of what "book write_protect" sounds like from a code perspective?

2022-05-16 21:20 UTC, peterdelevoryas commented
Oops, sorry @chen-iris, I force pushed to openbmc-qemu and messed up your branch. My bad. :(

2022-05-16 21:25 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +    /* W# is just a single pin. */
Yeah, I understand the confusion. See the [datasheet](https://media-www.micron.com/-/media/client/global/documents/products/data-sheet/nor-flash/serial-nor/m25p/m25p80.pdf?rev=c3236118aac04069a628d41fe50d26eb).

W# low is the restrictive mode. And, by the way, you still need to set the SRWD bit to 1,
or else users can just remove the write protections by rewriting the status register. This is also why this commit shouldn't include any actual write protections yet (in flash media writes or status register writes). We need the SRWD bit first.

<img width="718" alt="Screen Shot 2022-05-16 at 2 22 30 PM" src="https://user-images.githubusercontent.com/8096834/168684775-e80d772e-0b25-4912-968a-b2d85f45ab8c.png">

2022-05-16 21:29 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +                            m25p80_write_protect_irq_handler, "W#", 1);
Yes that's correct. The attribute `bool write_protected` is not actually intended to represent the flash media being write protected, it's meant to represent the pin state. Perhaps a better name would be `bool write_protect_pin;` or something like that that's more explicit?

The reason we even have an attribute like this, instead of just using the GPIO attribute that we're adding in this line, is that there's no way to "get" the level of the pin from the QEMU GPIO model (afaict). There's a method for setting the GPIO (qemu_set_irq), but it just calls a function that handles the level change. As far as I know, the model author is supposed to store the pin level somewhere in the QEMU model. If you check out hw/gpio/aspeed_gpio.c, that's what they do for all the generic GPIO pins. They initialize an object like this, and store the level in a struct.

2022-05-16 22:16 UTC, chen-iris commented
> > I can't tell which polarity we are modeling and which way the QEMU code would tend to want to see it.  My inclination is that we would want to model the state of the function and not the state of the pin?
> 
> Hmmmm yeah I guess that makes sense. You're referring to the fact that "high" on the pin actually means "don't protect", and "low" is used to enable hardware protected mode, which is kind of the inverse of what "bool write_protect" sounds like from a code perspective?

The code should be updated now to correct this. Let me know what you think!

2022-05-17 23:15 UTC, peterdelevoryas requested changes
Actually, SRWD does not correspond to any pins going into the flash device (note: we didn't create any irq/gpio stuff). I would call it the "SRWD bit", not the "SRWD pin".

2022-05-18 23:38 UTC, peterdelevoryas approved these changes

2022-05-18 23:38 UTC, merged