hw: m25p80: add block protect bits
facebookarchive/openbmc-qemu-fork pull request #20
Opened 2022-05-24 17:25 UTC by chen-iris

Signed-off-by: Iris Chen <irischenlj@fb.com>

Adding BP0, BP1, BP2, BP3 for memory write protection

2022-05-24 18:39 UTC, peterdelevoryas requested changes

2022-05-24 18:39 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +    int block_protect_value = (s->block_protect3 << 3) |
Need an if-check for when this value is zero, to avoid shifting by a negative value, which is undefined behavior

2022-05-24 18:39 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +    int protected_area = 1 << (block_protect_value - 1);
Consider making the name reflect the units, e.g. `protected_sectors`

2022-05-24 18:39 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +    if (block_protect_value != 0 && addr > 511 - protected_area) {
This probably needs to be `addr > (s->pi->n_sectors - protected_area) * s->pi->sector_size)`, check with more testing/print statements

2022-05-24 18:39 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +        s->block_protect3 = extract32(s->data[0], 6, 1);
Maybe put an if statement around this last bit, so that it only applies to the n25q256a

2022-05-24 18:39 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +        s->data[0] |= (!!s->block_protect3) << 6;
Same here, needs an if check so it doesn't pull this bit from the Top/Bottom bit on other devices.

2022-05-24 18:39 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +        s->block_protect3 = extract32(s->data[0], 6, 1);
To do this, you can add a flag like "BP3_BIT6", add that flag to the entry for n25q256a in hw/block/m25p80.c's flash device table, and use that flag in the if statement here, similar to the Linux kernel driver:

```
/* Status Register bits. */
#define SR_WIP                  BIT(0)  /* Write in progress */
#define SR_WEL                  BIT(1)  /* Write enable latch */
/* meaning of other SR_* bits may differ between vendors */
#define SR_ macro SR_BP3          T(2)  /* Block protect 0 */
#define SR_                       T(3)  /* Block protect 1 */
#define SR_ #define SR_BP3 BIT(5) T(4)  /* Block protect 2 */
#define SR_BP3                  BIT(5)  /* Block protect 3 */
#define SR_TB_BIT5              BIT(5)  /* Top/Bottom protect */
#define SR_BP3_BIT6             BIT(6)  /* Block protect 3 */
#define SR_TB_BIT6              BIT(6)  /* Top/Bottom protect */
#define SR_SRWD                 BIT(7)  /* SR write protect */
/* Spansion/Cypress specific status bits */
#define SR_E_ERR                BIT(5)
#define SR_P_ERR                BIT(6)

#define SR1_QUAD_EN_BIT6        BIT(6)

#define SR_BP_SHIFT             2
```

2022-05-24 18:39 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +    writel(ASPEED_FLASH_BASE, make_be32(my_page_addr));
Notes from in-person code review: We needed something more like this:

```
static void test_write_block_protect(void)
{
    uint32_t my_page_addr = 0x325ab * FLASH_PAGE_SIZE; /* beyond 16MB */
    printf("my_page_addr = 0x%08x\n", my_page_addr);
    printf("my_page_addr be32 = 0x%08x\n", make_be32(my_page_addr));

    spi_ce_ctrl(1 << CRTL_EXTENDED0);

    spi_conf(CONF_ENABLE_W0);

    spi_ctrl_start_user();
    writeb(ASPEED_FLASH_BASE, WREN);
    writeb(ASPEED_FLASH_BASE, WRSR);
    writeb(ASPEED_FLASH_BASE, 0xC);
    writeb(ASPEED_FLASH_BASE, EN_4BYTE_ADDR);
    writeb(ASPEED_FLASH_BASE, WREN);
    spi_ctrl_stop_user();

    /* move out USER mode to use direct writes to the AHB bus */
    spi_ctrl_setmode(CTRL_WRITEMODE, PP);
    for (int i = 0; i < FLASH_PAGE_SIZE / 4; i++) {
        writel(ASPEED_FLASH_BASE + i * 4, 0xabcdef12);
    }
    //writel(ASPEED_FLASH_BASE, make_be32(my_page_addr));
}
```

2022-05-25 05:05 UTC, peterdelevoryas requested changes

2022-05-25 05:05 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +#define SR_BP3_BIT6 BIT(6)  /* Block protect 3 */
So, this constant is correct, but there's actually two constants related to BP3_BIT6 in Linux. The other one is this:

```
enum spi_nor_option_flags {
        SNOR_F_HAS_SR_TB        = BIT(0),
        SNOR_F_NO_OP_CHIP_ERASE = BIT(1),
        SNOR_F_BROKEN_RESET     = BIT(2),
        SNOR_F_4B_OPCODES       = BIT(3),
        SNOR_F_HAS_4BAIT        = BIT(4),
        SNOR_F_HAS_LOCK         = BIT(5),
        SNOR_F_HAS_16BIT_SR     = BIT(6),
        SNOR_F_NO_READ_CR       = BIT(7),
        SNOR_F_HAS_SR_TB_BIT6   = BIT(8),
        SNOR_F_HAS_4BIT_BP      = BIT(9),
        SNOR_F_HAS_SR_BP3_BIT6  = BIT(10), <<<<<
        SNOR_F_IO_MODE_EN_VOLATILE = BIT(11),
        SNOR_F_SOFT_RESET       = BIT(12),
        SNOR_F_SWP_IS_VOLATILE  = BIT(13),
};
```

So, you copied the "SR_" constant, which corresponds to the exact bit in the status register (SR) that it's referring to (BIT6 == BIT(6)). SNOR_F_HAS_SR_BP3_BIT6 is an enum variant that represents an option in the flash specification that indicates the flash model has BP3 in the bit 6 offset.

So, SNOR_F_HAS_SR_BP3_BIT6 is used in the flash model info table to represent metadata, and SR_BP3_BIT6 is used to get/set the BP3 bit in the status register.

I'm just pointing this out because I think it would probably be preferable to also copy the Linux driver in this respect. Unfortunately, whoever added ER_4K and ER_32K did _not_ introduce an enum, they just used `#define`'s.

Ultimately I think I would suggest adding an enum similar to the driver, and changing ER_4K and ER_32K to be BIT(0) and BIT(1). And then the BP3 flag could be BIT(2). Cause they all have to be mutually exclusive bits in the flags field.

2022-05-25 05:05 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +#define SR_BP3_BIT6 BIT(6)  /* Block protect 3 */
Actually, just noticed: EEPROM already took BIT(2), BP3's flag would have to be BIT(3). The confusion that I'm having figuring this out is all the more reason it should be an enum of options, so that it's clear exactly how many option flags there are.

2022-05-25 05:05 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +    }
I would actually suggest avoiding casting of any kind (explicit or implicit). In this case, `n_sectors` is a `uint32_t`, so we should just make sure that all the other values we do arithmetic with it are uint32_t's too. Maybe this could work:

```
uint32_t block_protect_value = ...;
...
    uint32_t num_unprotected_sectors = MAX(0, s->pi->n_sectors - (1 << (block_protect_value - 1)));
```

Also, it's not totally clear what the difference is between `num_unprotected_sectors` and `unprotected_sectors` just from the variable names. I think `unprotected_sectors` should probably be changed to something that indicates the units are bytes, e.g. `unprotected_bytes` or `unprotected_size`.

Otherwise I think it looks right! Comparing the address to the unprotected value threw me for a loop though lol (I was expecting it to be compared to the protected value), but that's ok.

2022-05-25 05:05 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +        if (s->pi->flags & SR_BP3_BIT6) {
Nice! Yeah this is exactly what I was thinking.

2022-05-25 05:05 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +    }
Hmmmmmm ok so I haven't read everything in this function yet, but I'm already confused at this. I would not expect this to work.

2022-05-25 16:50 UTC, chen-iris commented on hw/block/m25p80.c
> +    }
yup, this is a good point. I will rename and update the types

2022-05-25 19:07 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +#define SR_BP3_BIT6 BIT(6)  /* Block protect 3 */
Actually, we won't need the SR_BP3_BIT6 flag.

2022-05-25 19:07 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +    }
Actually I just didn't understand the direct write mode, this is fine.

2022-05-25 19:07 UTC, peterdelevoryas requested changes

2022-05-25 19:07 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +
Need to bulk erase at the start, or add bulk erase to flash_reset()

2022-05-25 20:12 UTC, zhdaniel12 commented on hw/block/m25p80.c
> +        if (addr >= unprotected_sectors) {
do we need take count of BT bit (Bottom vs. Top)?

2022-05-25 20:12 UTC, zhdaniel12 commented on hw/block/m25p80.c
> +        if (addr >= unprotected_size) {
I think there's a BT bit which control the BP bits protecting the bottom (low address) or top (high address) part.

2022-05-25 21:27 UTC, peterdelevoryas requested changes

2022-05-25 21:27 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +        if (s->pi->n_sectors - num_sectors_in_addr <= num_protected_sectors) {
`s->pi->n_sectors - num_protected_sectors <= sector` might be more clear: you're doing this correctly, it's just that `N - addr` is essentially calculating the address starting from the top, and `num_protected_sectors` is relative to the bottom (zero).

2022-05-25 21:52 UTC, merged