hw: m25p80: add top bottom bit for write protect
facebookarchive/openbmc-qemu-fork pull request #21
Opened 2022-05-26 03:37 UTC by chen-iris

Signed-off-by: Iris Chen <irischenlj@fb.com>

2022-05-26 17:57 UTC, zhdaniel12 requested changes

2022-05-26 17:57 UTC, zhdaniel12 commented on hw/block/m25p80.c
> +            s->data[0] |= (!!s->top_bottom_bit) << 5;
Is the BT bit only available when there's BP3?
please check openbmc verified boot code : flash-spl.c::doheap()
We need support MT, WB, GD and MX 4 flash vendor's SPI-NOR in QEMU.

2022-05-26 18:12 UTC, peterdelevoryas requested changes
Overall looks good! Awesome work, I'm really excited to test this out with OpenBMC now. We should be able to try booting 2 OpenBMC unsigned images, and seeing what happens in Verified Boot. It should be able to avoid getting stuck in recovery boot, if the images are unsigned and unlocked.

2022-05-26 18:12 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +static void check_memory(uint32_t addr,
I think that instead of passing in the `page` buffer as a parameter, we could just declare it as a local stack variable here.

2022-05-26 18:12 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +static void check_memory(uint32_t addr,
Also, I think `check_memory` might be too generic of a name for this function. We probably want something that indicates we're specifically reading 1 page and comparing it to a 32 bit value.

2022-05-26 18:12 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +}
Similar comment here: `write_memory` might be too generic. This page is pretty similar to the `memset` function in libc, just for a page, and with a 32-bit value.

```
       memset - fill memory with a constant byte

SYNOPSIS
       #include <string.h>

       void *memset(void *s, int c, size_t n);

DESCRIPTION
       The memset() function fills the first n bytes of the memory area pointed to by s with the constant byte c.
```

Something that might be instantly recognizable to people is `memset_page`, but I'm not really sure, I'll leave it up to you to decide. We might also want to make sure that it sounds like it complements the `check_memory` function.

2022-05-26 18:12 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +}
Hmmm should we really be running a bulk erase in this function? I know that it's probably needed to make the test pass, but when the function is called `write_block_protect_bits`, I would expect it to just modify the status register, not the flash media. Same thing with enabling 4 byte addressing, I think we'd probably like to keep that separate from this.

Also, by writing the "write_value" directly to the status register, we'll also be overwriting the SRWD bit and/or the top/bottom bit. We should either make this function `write_status_register` if we really just want to write the entire status register, or read the status register first to make sure we don't overwrite the other bits in the status register. For example:

```
uint8_t status_register = ... execute a RDSR command ...

// Clear the existing BP bits
status_register &= ~0x5c; // 0x5c == 0b01011100, ~0x5c == 0b10100011.
// Set the new BP bits
status_register |= (write_value & 0x5c);

...
writeb(ASPEED_FLASH_BASE, WRSR);
writeb(ASPEED_FLASH_BASE, status_register);
...
```

2022-05-26 18:12 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +            s->top_bottom_bit = extract32(s->data[0], 5, 1);
I suppose if a flash device has BP3_BIT6, it probably has the top bottom bit in position 5...However, I think the Linux kernel models this with a separate flag, and a separate if statement. Idk, I'll leave it up to you if you think we should add an additional TB flag and put this extract code in a separate if block that checks the TB flag instead of BP3_BIT6.

```
num spi_nor_option_flags {
        SNOR_F_HAS_SR_TB        = BIT(0), <<<<<<<<<<<<<<<

        SNOR_F_NO_OP_CHIP_ERASE = BIT(1),
        SNOR_F_BROKEN_RESET     = BIT(2),
        SNOR_F_4B_OPCODES       = BIT(3),
        SNOR_F_HAS_4BAIT        = BIT(4),
        SNOR_F_HAS_LOCK         = BIT(5),
        SNOR_F_HAS_16BIT_SR     = BIT(6),
        SNOR_F_NO_READ_CR       = BIT(7),

        SNOR_F_HAS_SR_TB_BIT6   = BIT(8), <<<<<<<<<<

        SNOR_F_HAS_4BIT_BP      = BIT(9),
        SNOR_F_HAS_SR_BP3_BIT6  = BIT(10),
        SNOR_F_IO_MODE_EN_VOLATILE = BIT(11),
        SNOR_F_SOFT_RESET       = BIT(12),
        SNOR_F_SWP_IS_VOLATILE  = BIT(13),
};
```

2022-05-26 18:21 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +            s->data[0] |= (!!s->top_bottom_bit) << 5;
Yeah, this same issue also applies to BP3. We should make sure that it works with all the different flash manufacturers we use. But, the aspeed_smc-test.c currently only tests a Micron device, so I think Iris was just going to start by implementing it for Micron.

We should also update aspeed_smc-test.c to verify multiple flash devices, so that we can verify the different behavior for each manufacturer.

2022-05-26 18:26 UTC, chen-iris commented on tests/qtest/aspeed_smc-test.c
> +static void check_memory(uint32_t addr,
very good point!

2022-05-26 18:31 UTC, chen-iris commented on tests/qtest/aspeed_smc-test.c
> +static void check_memory(uint32_t addr,
How is something like `verify_page_memory`?

2022-05-26 18:36 UTC, chen-iris commented on tests/qtest/aspeed_smc-test.c
> +}
Okay, currently I have: 
`mem_set_page` and `mem_verify_page`. What do you think?

2022-05-26 18:38 UTC, chen-iris commented on hw/block/m25p80.c
> +            s->top_bottom_bit = extract32(s->data[0], 5, 1);
Ah, I think you're right and it's much cleaner to use a separate if block to check the TB flag

2022-05-26 18:48 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +}
Yeah that sounds good!

2022-05-26 20:25 UTC, chen-iris commented on hw/block/m25p80.c
> +            s->data[0] |= (!!s->top_bottom_bit) << 5;
Discussed offline that this PR only supports bits for MT flash only. Further PRs may be submitted which support other devices.

2022-05-26 23:08 UTC, peterdelevoryas requested changes

2022-05-26 23:08 UTC, peterdelevoryas commented on hw/block/m25p80.c
>  #define SNOR_F_HAS_SR_BP3_BIT6 BIT(10)
BIT(0) == 1 == ER_4K

Maybe do SNOR_F_HAS_SR_TB BIT(2)

2022-05-26 23:09 UTC, peterdelevoryas requested changes

2022-05-26 23:09 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +    } test_cases[] = {
This is definitely what I had in mind, but I think the test case struct is a little obtuse, and still has some repeated information. You can kind of tell that there's repeated information, because you repeated the "page_addr", "page_write", and "check_page" variables three times.

Taking a step back: I see that for each BP test case, we're doing 3 tests:

1. Verify that we can write (or can't write) to the first sector.
2. Verify that we can write to the sector immediately before the protection boundary.
3. Verify that we can write to the sector immediately after the protection boundary.

We could just do a for-loop over all the BP combinations we want to test and verify these things, right? We don't really need to hard-code the page addresses, we could calculate them from the BP bits right? Because, we can calculate the protection boundary
from the BP bits, and then do -1 after that. Maybe we need an additional less-than-zero or greater-than-n_sectors check when BP==0 or BP==0b1111.

Also, I just realized: C actually supports binary literals, so instead of 0x5c/etc you can do 0b01011100 if you want.

2022-05-28 00:41 UTC, zhdaniel12 approved these changes

2022-05-31 17:51 UTC, peterdelevoryas requested changes

2022-05-31 17:51 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +        }
I think you could simply this to

`bp_bits = ((i & 0b1000) << 6) | ((i & 0b0111) << 2)`

Right? Not totally sure

2022-05-31 17:51 UTC, peterdelevoryas commented on hw/block/m25p80.c
> -    if (block_protect_value > 0) {
Oh wait, I think I missed this in the previous review for the BP bits: why are we checking that `block_protect_value > 0` if it's unsigned? This will always be true right?

2022-05-31 17:51 UTC, peterdelevoryas commented on hw/block/m25p80.c
> -    if (block_protect_value > 0) {
Ohhhh sorry, I get it. We're checking that it's not zero. Nvm sorry lol, my brain is still waking up after the weekend.

2022-05-31 18:24 UTC, peterdelevoryas requested changes

2022-05-31 18:24 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +        writel(addr + i * 4, write_value);
Maybe this should be `writel(ASPEED_FLASH_BASE + addr + i * 4, ...)`, so that the caller doesn't have to use ASPEED_FLASH_BASE + addr? Because, mem_verify_page seems to automatically add ASPEED_FLASH_BASE.

2022-05-31 18:24 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +        } else if (i > 9) {
I'm not sure about the if-statements here: I think it would be nice if we could find a way to unify them, but I realize it's probably pretty hard.

Stepping back: could we just iterate over all sectors/pages in the whole device in a single for loop? And, determine if it should be protected or not by using the
BP bits and T/B bit to compute a range (start and end) that is protected?

```
uint32_t top_bottom_bit = < Get T/B state >
uint32_t num_protected_sectors = bp_bits ? MAX(1 << (bp_bits - 1), n_sectors) : 0;
uint32_t protection_start = top_bottom_bit ? 0 : n_sectors - num_protected_sectors;
uint32_t protection_end = protection_start + num_protected_sectors;

for (int sector = 0; sector < n_sectors; sector++) {
    uint32_t addr = sector * sector_size;
    mem_verify_page(addr, 0xffffffff);
    mem_set_page(ASPEED_FLASH_BASE + addr, make_be32(0xabcdef12));

    uint32_t expected_value = protection_start <= sector && sector < protection_end
                            ? 0xffffffff : make_be32(0xabcdef12));
    mem_verify_page(addr, expected_value);
}
```

Idk, maybe no exactly this, but I just realized that the range thing (start, end) for the protected area might be useful to unify all the different code paths.

2022-05-31 18:43 UTC, chen-iris commented on tests/qtest/aspeed_smc-test.c
> +        }
So, this doesn't work but `bp_bits = (((i + 1) & 0b1000) << 3) | (((i + 1) & 0b0111) << 2)` does since we need to account for the next iteration

2022-05-31 19:58 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +        }
Oh, you're right, but I meant more like we could compute bp_bits at the start of each loop, so that we don't have to worry about mutation/etc.

2022-05-31 22:06 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +}
Oh perfect, and this is a good name for the function. Nice job recognizing that it's similar to read_page_mem, I didn't notice that, I should have suggested that in the first place when I was telling you to rename stuff everywhere.

2022-05-31 22:08 UTC, peterdelevoryas approved these changes
This is looking great! I think this test will be great when we submit it upstream. I'm curious how long it takes to run exactly (hopefully not too long), but if necessary, it will be easy to skip some sectors if we want in the future.

2022-05-31 22:25 UTC, peterdelevoryas commented
I see it runs in 129.28s, that may or may not be too long for upstream, but we can tackle that later.

2022-05-31 22:25 UTC, merged