hw: m25p80: fixing individual test failure when tests are running in …
facebookarchive/openbmc-qemu-fork pull request #23
Opened 2022-05-31 22:57 UTC by chen-iris

…isolation

Signed-off-by: Iris Chen <irischenlj@fb.com>

There exists some dependencies between the tests causing some tests to fail in isolation but pass when run altogether. 

This patch fixes that and allows all the tests to run in isolation by adding bulk erase into `reset_memory` and fixing the tests so they do not depend on each other. 

The problem before: (example of `"/ast2400/smc/write_page_mem"` from main)
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/46090544/171253415-f29c3676-fadd-472f-807a-4459b1e30015.png">

Now: 
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/46090544/171296533-8b268473-bb69-4c00-b4e0-5540ec73033b.png">

2022-05-31 23:24 UTC, peterdelevoryas requested changes

2022-05-31 23:24 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +    memset(s->storage, 0xff, s->size);
Oh, I think this actually _isn't_ correct. Only BULK ERASE should do this. I guess RESET MEMORY is a different command, that's just meant to reset the device's state or something. But I'm relatively certain that it wouldn't actually reset the device's storage.

2022-05-31 23:24 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +    spi_ctrl_setmode(CTRL_WRITEMODE, PP);
How come we're entering WRITE mode while we're still in USER mode?

2022-05-31 23:24 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> -        g_assert_cmphex(page[i], ==, 0x0);
I think we should probably keep this, cause we want to verify the initial state of everything, but we shouldn't expect zeroes anymore, I think we would expect 0xff's right, from the BULK ERASE? We would also want to update the comment to reflect that the backend _is_ initialized, from the BULK ERASE.

2022-05-31 23:24 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
>      }
After writing the 0xabcdef12 page, we might want to verify that it was written successfully by reading back the page and verifying it is 0xabcdef12's

2022-05-31 23:24 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +    spi_ctrl_stop_user();
Same thing here, I don't think entering WRITE mode while we're in USER mode makes sense. Those three modes should be mutually exclusive. You can read more about this in the Aspeed documentation.

2022-05-31 23:24 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
>      }
Probably also need to verify this page got written successfully too (like the previous one I left a comment on)

2022-05-31 23:24 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> -    flash_reset();
Mmmmm how come we're removing flash_reset()?

2022-05-31 23:24 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +    }
I think this test was actually specifically written with the intent of testing write_page, and not write_page_mem, couldn't we use USER mode instead of WRITE mode here?

2022-05-31 23:47 UTC, chen-iris commented on tests/qtest/aspeed_smc-test.c
> -    flash_reset();
oops, this is an error on my part!

2022-06-02 23:55 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +        g_assert_cmphex(page[i], ==, some_page_addr + i * 4);
Oh this is perfect, great job.

2022-06-02 23:56 UTC, peterdelevoryas commented on tests/qtest/aspeed_smc-test.c
> +    flash_reset();
Nice, yep this is what I had in mind.

2022-06-02 23:56 UTC, peterdelevoryas approved these changes

2022-06-02 23:56 UTC, merged