hw: m25p80: use upstream suggestions -  move write_enable to decode_n…
facebookarchive/openbmc-qemu-fork pull request #27
Opened 2022-06-09 21:16 UTC by chen-iris

…ew_cmd

Match suggestions given by https://lore.kernel.org/qemu-devel/20220609192201.GC10629@fralle-msi/

Signed-off-by: Iris Chen <irischenlj@fb.com>

2022-06-09 21:25 UTC, peterdelevoryas approved these changes
I think this is right, and it's pretty simple actually, nice job. It's gonna be a nightmare when I have to rebase all these changes and merge with the upstream and remember what's what.

2022-06-10 20:50 UTC, peterdelevoryas requested changes

2022-06-10 20:50 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +    .needed = vmstate_m25p80_status_register_write_disabled_needed,
I don't think we should include a .needed function, we should just leave it false.

2022-06-10 20:50 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +    .version_id = 1,
I also think maybe the version_id should be 2, but not totally sure.

2022-06-10 20:50 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +    .name = "m25p80/status_register_write_disabled",
We should put both vmstate attributes in a single subsection, instead of having two separate subsections.

2022-06-10 23:00 UTC, chen-iris commented
Updated based on all suggestions: 
- Combine into one VMState: let me know if you have feedback with regards to the naming

2022-06-11 02:55 UTC, merged