hw: m25p80: Fixing issue with spi gpio driver where miso is being cle…
facebookarchive/openbmc-qemu-fork pull request #34
Opened 2022-06-24 18:31 UTC by chen-iris

…ared

Signed-off-by: Iris Chen <irischenlj@fb.com>

A couple fixes for the SPI GPIO driver: 
- Need to reset the device
- Fixing setting the miso value as it is being incorrectly cleared by the kernel driver (see comments)

2022-06-24 19:16 UTC, zhdaniel12 requested changes
let make this PR focusing on handle the overwrite issue only.

Another general comment is that: this fix is still just a workaround, there's still potential that host driver somehow try to control other GPIO pin (i.e. GPIOX7) within the SPI bitbang sampling critical section (set clk, and read miso)
           thread1 (spi bitbang)          threadX (using GPIOX7)
T0       set clk (set miso)
T1       --------------------------- set GPIOX7 (overwrite miso)
T2        read miso

2022-06-24 19:16 UTC, zhdaniel12 commented on hw/ssi/spi_gpio.c
> +    s->output_byte = 0xFF;
I think this is a debug change not needed here

2022-06-24 19:16 UTC, zhdaniel12 commented on hw/arm/aspeed.c
> +    device_legacy_reset(m25p80);
this change does not related to overwrite, it is relate how to add the device. 
let's put this in another PR, and @peterdelevoryas do you know what is the best way to get this device reset?

2022-06-24 22:39 UTC, peterdelevoryas commented on hw/arm/aspeed.c
> +    device_legacy_reset(m25p80);
Oh, yeah, I added a comment in the other PR before seeing this. I think we should use sysbus_realize(DEVICE(spi_gpio), &error_fatal); instead of qdev_realize. The QEMU reset works by resetting all the devices connected to the same bus: by doing qdev_realize(..., NULL, ...) we're not on the bus, so we don't get reset. But if we use sysbus_realize, it adds the device as a child of the global singleton system bus.

2022-06-24 22:39 UTC, peterdelevoryas commented on hw/arm/aspeed.c
> +    device_legacy_reset(m25p80);
That's my fault, I'm the one who initially suggested qdev_realize, my bad

2022-06-27 16:43 UTC, zhdaniel12 approved these changes

2022-06-27 18:34 UTC, merged