hw: m25p80: add device reset for m25p80 in the spi gpio controller
facebookarchive/openbmc-qemu-fork pull request #35
Opened 2022-06-24 21:51 UTC by chen-iris

Signed-off-by: Iris Chen <irischenlj@fb.com>

m25p80 needs to be reset. Looking for suggestions on better ways to do this

2022-06-24 22:37 UTC, peterdelevoryas requested changes

2022-06-24 22:37 UTC, peterdelevoryas commented on hw/arm/aspeed.c
> +    device_legacy_reset(m25p80);
The right thing to do is actually probably to call sysbus_realize(DEVICE(spi_gpio), &error_fatal);, which should put it on the main system bus, and then it will get reset at the same time as everything else. This is too early.

2022-06-27 17:00 UTC, zhdaniel12 commented on hw/arm/aspeed.c
> +    device_legacy_reset(m25p80);
Oh, this is a good suggestion. I am actually trying to figure out why the flash devices connected on aspeed_smc SPI bus get reset, but this flash device on spi_gpio bus does not.

2022-06-27 18:35 UTC, peterdelevoryas approved these changes

2022-06-27 18:58 UTC, peterdelevoryas commented
SpiGpio also needs to be a SysBusDevice in order to use sysbus_realize. Right now it's just a Device.

2022-06-27 19:06 UTC, peterdelevoryas commented
Try this, I think you can use sysbus_realize, but you need to change it to a SysBusDevice.

The spi_gpio_reset part doesn't need to be included, I just used it to verify that the reset function gets called.

```
diff --git a/hw/arm/aspeed.c b/hw/arm/aspeed.c
index fb6b80c9c4..6f6898cff7 100644
--- a/hw/arm/aspeed.c
+++ b/hw/arm/aspeed.c
@@ -397,7 +397,7 @@ static void aspeed_machine_init(MachineState *machine)

     SpiGpioState *spi_gpio = SPI_GPIO(qdev_new(TYPE_SPI_GPIO));
     spi_gpio->aspeed_gpio = &bmc->soc.gpio;
-    qdev_realize(DEVICE(spi_gpio), NULL, &error_fatal);
+    sysbus_realize(SYS_BUS_DEVICE(spi_gpio), &error_fatal);

     DeviceState *m25p80 = qdev_new("n25q256a");
     qdev_realize(m25p80, BUS(spi_gpio->spi), &error_fatal);
diff --git a/hw/ssi/spi_gpio.c b/hw/ssi/spi_gpio.c
index b829b7d87f..06700a10f0 100644
--- a/hw/ssi/spi_gpio.c
+++ b/hw/ssi/spi_gpio.c
@@ -157,16 +157,22 @@ static void spi_gpio_realize(DeviceState *dev, Error **errp)
     qdev_init_gpio_out_named(dev, &s->cs_output_pin, "SPI_CS_out", 1);
 }

+static void spi_gpio_reset(DeviceState *dev)
+{
+    printf("%s\n", __func__);
+}
+
 static void SPI_GPIO_class_init(ObjectClass *klass, void *data)
 {
     DeviceClass *dc = DEVICE_CLASS(klass);

     dc->realize = spi_gpio_realize;
+    dc->reset = spi_gpio_reset;
 }

 static const TypeInfo SPI_GPIO_info = {
     .name           = TYPE_SPI_GPIO,
-    .parent         = TYPE_DEVICE,
+    .parent         = TYPE_SYS_BUS_DEVICE,
     .instance_size  = sizeof(SpiGpioState),
     .class_init     = SPI_GPIO_class_init,
 };
diff --git a/include/hw/ssi/spi_gpio.h b/include/hw/ssi/spi_gpio.h
index 9111640d6c..2094a45217 100644
--- a/include/hw/ssi/spi_gpio.h
+++ b/include/hw/ssi/spi_gpio.h
@@ -33,7 +33,7 @@
 OBJECT_DECLARE_SIMPLE_TYPE(SpiGpioState, SPI_GPIO);

 struct SpiGpioState {
-    DeviceState parent;
+    SysBusDevice parent;
     SSIBus *spi;
     AspeedGPIOState *aspeed_gpio;
```

2022-06-27 20:41 UTC, chen-iris commented
> Try this, I think you can use sysbus_realize, but you need to change it to a SysBusDevice.
> 
> The spi_gpio_reset part doesn't need to be included, I just used it to verify that the reset function gets called.
> 
> ```
> diff --git a/hw/arm/aspeed.c b/hw/arm/aspeed.c
> index fb6b80c9c4..6f6898cff7 100644
> --- a/hw/arm/aspeed.c
> +++ b/hw/arm/aspeed.c
> @@ -397,7 +397,7 @@ static void aspeed_machine_init(MachineState *machine)
> 
>      SpiGpioState *spi_gpio = SPI_GPIO(qdev_new(TYPE_SPI_GPIO));
>      spi_gpio->aspeed_gpio = &bmc->soc.gpio;
> -    qdev_realize(DEVICE(spi_gpio), NULL, &error_fatal);
> +    sysbus_realize(SYS_BUS_DEVICE(spi_gpio), &error_fatal);
> 
>      DeviceState *m25p80 = qdev_new("n25q256a");
>      qdev_realize(m25p80, BUS(spi_gpio->spi), &error_fatal);
> diff --git a/hw/ssi/spi_gpio.c b/hw/ssi/spi_gpio.c
> index b829b7d87f..06700a10f0 100644
> --- a/hw/ssi/spi_gpio.c
> +++ b/hw/ssi/spi_gpio.c
> @@ -157,16 +157,22 @@ static void spi_gpio_realize(DeviceState *dev, Error **errp)
>      qdev_init_gpio_out_named(dev, &s->cs_output_pin, "SPI_CS_out", 1);
>  }
> 
> +static void spi_gpio_reset(DeviceState *dev)
> +{
> +    printf("%s\n", __func__);
> +}
> +
>  static void SPI_GPIO_class_init(ObjectClass *klass, void *data)
>  {
>      DeviceClass *dc = DEVICE_CLASS(klass);
> 
>      dc->realize = spi_gpio_realize;
> +    dc->reset = spi_gpio_reset;
>  }
> 
>  static const TypeInfo SPI_GPIO_info = {
>      .name           = TYPE_SPI_GPIO,
> -    .parent         = TYPE_DEVICE,
> +    .parent         = TYPE_SYS_BUS_DEVICE,
>      .instance_size  = sizeof(SpiGpioState),
>      .class_init     = SPI_GPIO_class_init,
>  };
> diff --git a/include/hw/ssi/spi_gpio.h b/include/hw/ssi/spi_gpio.h
> index 9111640d6c..2094a45217 100644
> --- a/include/hw/ssi/spi_gpio.h
> +++ b/include/hw/ssi/spi_gpio.h
> @@ -33,7 +33,7 @@
>  OBJECT_DECLARE_SIMPLE_TYPE(SpiGpioState, SPI_GPIO);
> 
>  struct SpiGpioState {
> -    DeviceState parent;
> +    SysBusDevice parent;
>      SSIBus *spi;
>      AspeedGPIOState *aspeed_gpio;
> ```

Updated.

2022-06-27 20:43 UTC, peterdelevoryas approved these changes

2022-06-27 20:43 UTC, merged