draft
facebookarchive/openbmc-qemu-fork pull request #36
Opened 2022-06-24 23:06 UTC by chen-iris

Signed-off-by: Iris Chen <irischenlj@fb.com>

2022-06-24 23:43 UTC, peterdelevoryas requested changes

2022-06-24 23:43 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +            r = m25p80_transfer8(ss, 0xff); /* return next byte */
I left comments on a previous version, but I think it got sweeped away.

Why does this need to be in m25p80.c? Can't we just call ssi_transfer two times in spi-gpio.c? Won't it be doing literally the exact same thing?

Also, if you added this, wouldn't you have to do it for every command, not just JEDEC_READ?

2022-06-25 00:24 UTC, zhdaniel12 requested changes
1. All device can access to it's parent bus, thus the we may not need add preread attribute in SSIPeripheral 
2. move the SSIBus define to ssi.h is OK.
3. use a wrapper function to inject the logic to handle pre-read.
`
m25p80_transfer8_ex() {
     SSIBus *ssibus = SSI_BUS(qdev_get_parent_bus(DEVICE(s));     
     r = m25p80_transfer8();
     if ( ssibus->preread && ( s->state == STATE_READ || s->state == STATE_READING_DATA ) {
          r = m25p80_transfer8();     
     }
     return r;
}

// don't forget to change the k->transfer = m25p80_transfer8_ex;
`

2022-06-25 00:24 UTC, zhdaniel12 commented on hw/block/m25p80.c
> +        if (ss->preread && s->cmd_in_progress == JEDEC_READ &&
I am suggesting you create a wrapper function and call into this real m25p80_transfer8 to capture all cases which will change the state to STATE_READ and STATE_READING_DATA. 
i.e. case STATE_COLLECTING_DATA:
    case STATE_COLLECTING_VAR_LEN_DATA 
after multi-bytes command received finished, state normally may change to read.

2022-06-25 01:02 UTC, zhdaniel12 commented on hw/block/m25p80.c
> +            r = m25p80_transfer8(ss, 0xff); /* return next byte */
the hacking here is feed the device with a dummy byte to read ahead of the output data.
the whole transaction with normal byte I/O controller (i.e. aspeed-smc) looks like this
MOSI:  <cmd-byte>     .... <cmd-byte>                < dummy-byte> .... < dummy-byte>
MISO: <dummy-byte> ... <last-dummy-byte>    <output-byte>  .... < output-byte>
All MISO bytes are provided by the SSI Peripheral device.

with this pre-read hack and our spi_gpio controller
MOSI:  <cmd-byte>   .... <cmd-byte>                                                          < dummy-byte> .... < dummy-byte>
MISO: <First-byte>    ... <dummy-byte>   <Last-dummy-byte-dropped> <output-byte>  .... < output-byte>

The MISO dummy-bytes corresponding to MOSI input cmd bytes get hacked become
the first-byte is spi-gpio defined, all device provided dummy bytes shifted one byte right. Thus the last dummy byte get dropped by double call transfer.

2022-06-25 18:53 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +            r = m25p80_transfer8(ss, 0xff); /* return next byte */
Would it be possible to do the following in spi_gpio.c?

```
diff --git a/hw/ssi/spi_gpio.c b/hw/ssi/spi_gpio.c
index 401ee3802b..75b5795693 100644
--- a/hw/ssi/spi_gpio.c
+++ b/hw/ssi/spi_gpio.c
@@ -99,7 +99,8 @@ static void clk_set_level(void *opaque, int n, int level)
          * from the SPI device
          */
         if (s->clk_counter == 8) {
-            s->output_byte = ssi_transfer(s->spi, s->input_byte);
+            ssi_transfer(s->spi, s->input_byte);
+            s->output_byte = ssi_transfer(s->spi, 0xff);
             s->clk_counter = 0;
             s->input_byte = 0;
          } else {
```

2022-06-27 16:40 UTC, zhdaniel12 commented on hw/block/m25p80.c
> +            r = m25p80_transfer8(ss, 0xff); /* return next byte */
as my previous comments mentioned, we cannot do this. the code you suggested will do two transfer for every input byte, this is not what we want.

2022-06-27 17:14 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +            r = m25p80_transfer8(ss, 0xff); /* return next byte */
I think I understand what you mean: so, with JEDEC READ, we have:

```
MOSI: 9f 00 00 00
MISO: 00 20 ba 19
```

These are the function calls:

```
0x00 = ssi_transfer(0x9f)
0x20 = ssi_transfer(0x00)
0xba = ssi_transfer(0x00)
0x19 = ssi_transfer(0x00)
```

But with the way the code is right now, this doesn't work:
```
MOSI: 9f 00 00 ...
MISO: 00 00 20 ...
        |  ^0x20 = ssi_transfer(0x00)
        ^0x00 = ssi_transfer(0x9f)
```

So, we need to fix the transition between reading and writing, right? I think I see what you guys mean.

2022-06-27 18:52 UTC, zhdaniel12 approved these changes
You may consider put following explain as the comments in transfer8_ex.

2022-06-27 18:52 UTC, peterdelevoryas commented on hw/block/m25p80.c
> +    uint8_t curr_state = s->state;
This is kind of confusing naming, it's more like prev_state and curr_state. curr_state is not actually the current state of the device when it's used.

2022-06-27 19:04 UTC, chen-iris commented on hw/block/m25p80.c
> +    uint8_t curr_state = s->state;
Sure, I can change it to prev_state and curr_state. I thought curr_state and next_state because we call m25p80_transfer8 in between

2022-06-27 19:10 UTC, zhdaniel12 commented on hw/block/m25p80.c
> +            r = m25p80_transfer8(ss, 0xff); /* return next byte */
yes, the reason we need to fix the transaction between reading and writing is because we arbitrary insert a first output byte in the transaction, so shift the whole output bytes (timeline) one byte right. 
if we use FF as the arbitrary first byte, the jedec-id read transaction will look like following 
MOSI: 9f  00 00 00 00 00 00
MISO: FF 00 20 ba 19 00 00 
The host get the output is [00 20 BA 19 00 00] instead of expected [ 20 BA 19 00 00 00 ]

2022-06-27 21:06 UTC, peterdelevoryas approved these changes

2022-06-27 21:06 UTC, peterdelevoryas commented on hw/ssi/ssi.c
> -struct SSIBus {
I don't think the upstream will like this. We should be using a QOM property instead. But it's fine for now.

2022-06-27 21:07 UTC, merged